/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 1.12
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.evetech.esi;

import net.evetech.esi.models.BadRequest;
import net.evetech.esi.models.ErrorLimited;
import net.evetech.esi.models.Forbidden;
import net.evetech.esi.models.GatewayTimeout;
import net.evetech.esi.models.GetCharactersCharacterIdFittings200Ok;
import net.evetech.esi.models.InternalServerError;
import net.evetech.esi.models.PostCharactersCharacterIdFittingsCreated;
import net.evetech.esi.models.PostCharactersCharacterIdFittingsFitting;
import net.evetech.esi.models.ServiceUnavailable;
import net.evetech.esi.models.Unauthorized;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for FittingsApi
 */
@Ignore
public class FittingsApiTest {

    private final FittingsApi api = new FittingsApi();

    
    /**
     * Delete fitting
     *
     * Delete a fitting from a character  --- 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteCharactersCharacterIdFittingsFittingIdTest() throws Exception {
        Integer characterId = null;
        Integer fittingId = null;
        String datasource = null;
        String token = null;
        api.deleteCharactersCharacterIdFittingsFittingId(characterId, fittingId, datasource, token);

        // TODO: test validations
    }
    
    /**
     * Get fittings
     *
     * Return fittings of a character  ---  This route is cached for up to 300 seconds
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdFittingsTest() throws Exception {
        Integer characterId = null;
        String datasource = null;
        String ifNoneMatch = null;
        String token = null;
        List<GetCharactersCharacterIdFittings200Ok> response = api.getCharactersCharacterIdFittings(characterId, datasource, ifNoneMatch, token);

        // TODO: test validations
    }
    
    /**
     * Create fitting
     *
     * Save a new fitting for a character  --- 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void postCharactersCharacterIdFittingsTest() throws Exception {
        Integer characterId = null;
        PostCharactersCharacterIdFittingsFitting fitting = null;
        String datasource = null;
        String token = null;
        PostCharactersCharacterIdFittingsCreated response = api.postCharactersCharacterIdFittings(characterId, fitting, datasource, token);

        // TODO: test validations
    }
    
}
